package jp.bbo.becoandroid.Model.PhotoEditor

import android.util.Pair

class Sticker {

    fun sticker(): ArrayList<Pair<String, StickerName>> {
        val mPairList = ArrayList<Pair<String, StickerName>>()
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory1.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory2.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory3.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory4.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory5.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory6.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory7.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory8.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory9.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory10.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory11.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory12.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory13.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory14.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory15.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory16.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory17.png",
                StickerName.STICKER
            )
        )
        mPairList.add(
            Pair(
                "stickerthumbs/thumb_category/thumbcategory18.png",
                StickerName.STICKER
            )
        )
        return mPairList
    }
}